### ISSUE TITLE
Specs can't fit on screen.

### ISSUE THREAD

**Issue by keNNySOC** [AluminiumTech/Resource-Monitor#3]
So whenever i run Resource Monitor i can't see the full specs,so i would really love something like a scroll button to help me scroll up and down and view everything,as you can see by the photo i can't view everything,but can't scroll down
![9](https://cloud.githubusercontent.com/assets/21291309/18033705/0c5a4366-6d2c-11e6-9c48-6e20b2d704c7.PNG)t o

**Comment by AluminiumTech** [comment]
This should be fixed in the next version which uses a Tab based design. In case it doesn't please respond to this and tell me :).

**Comment by keNNySOC** [comment]
Sure will do

**Comment by AluminiumTech** [comment]
This should be fixed in Insider Preview 2017.0.8 .

Please let me know if it isn't fixed. I will consider this closed unless you encounter any further issues with this.
